<?php

/*
 * Implements hook_form_alter.
 *
 * Inlcude the javascript file to manage styles for CKEditor
 *
 * NOTE: This is a community contribute module that was provided in a thread, not a project page. As a result it has been moved to ASC custom modules so that it can be monitored internally.
 *
 */
function ckeditor_styles_wysiwyg_editor_settings_alter(&$settings, $context) {
  if ($context['profile']->editor == 'ckeditor') {
       $settings['stylesCombo_stylesSet'] = 'my_styles:' . base_path() . drupal_get_path('module', 'ckeditor_styles').'/ckeditor_styles.js';
  }
}

?>